### ISSUE TITLE
Не может найти JCAPIProvider

### ISSUE THREAD

**Issue by taleh007** [nashby/ms-capi#2]
Наткнулся на твое решение лаборатоных. Интересует вопрос -- как запустить:) Знаю, прошло 4 года, но блин, чем черт не шутит

**Comment by nashby** [comment]
Там в папку с проектом надо было положить .jar файл с библиотекой The Pheox JCAPI, но вряд ли ты сейчас её найдешь (я не нашел). Так что давай делай сам ;)

**Comment by taleh007** [comment]
В век интернета нельзя найти библиотеку. Супер:)
